/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/**/*.{ts,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        /* Smartify custom tokens */
        background: 'var(--color-bg)',
        card: 'var(--color-card)',
        'card-alt': 'var(--color-card-alt)',
        sidebar: 'var(--color-sidebar)',
        'sidebar-active': 'var(--color-sidebar-active)',
        border: 'var(--color-border)',
        accent: '#FF8400',
        'text-primary': 'var(--color-text-primary)',
        'text-secondary': 'var(--color-text-secondary)',
        'text-muted': 'var(--color-text-muted)',
        'gst-10': '#4ade80',
        'gst-10-bg': '#222924',
        'gst-unknown': '#FF8400',
        'gst-unknown-bg': '#291C0F',
        'gst-error': '#FF5C33',
        'gst-error-bg': '#24100B',
        agent: {
          extraction: '#FF8400',
          gst: '#4ade80',
          abn: '#B2B2FF',
          reconciliation: '#FF8400',
          reporting: '#4ade80',
          compliance: '#FF5C33',
        },
        /* Stitch tonal surface stack */
        'surface-lowest':  'var(--surface-lowest)',
        'surface-dim':     'var(--surface-dim)',
        'surface-low':     'var(--surface-low)',
        'surface':         'var(--surface)',
        'surface-mid':     'var(--surface-mid)',
        'surface-high':    'var(--surface-high)',
        'surface-highest': 'var(--surface-highest)',
        'surface-bright':  'var(--surface-bright)',
        /* Stitch token aliases (match stitch HTML class names 1:1) */
        'surface-container-lowest':  '#0E0E0E',
        'surface-container-low':     '#1C1B1B',
        'surface-container':         '#20201F',
        'surface-container-high':    '#2A2A2A',
        'surface-container-highest': '#353535',
        'primary-container':         '#FF8400',
        'on-primary':                '#4F2500',
        'on-primary-container':      '#5F2E00',
        'primary-fixed-dim':         '#FFB784',
        'primary-fixed':             '#FFDCC6',
        'tertiary':                  '#4DE082',
        'tertiary-container':        '#19BE64',
        'on-tertiary':               '#003919',
        'on-tertiary-container':     '#004520',
        'secondary-color':           '#7BD1FA',
        'error-chip':                '#FFB4AB',
        'error-container-chip':      '#93000A',
        'on-surface':      '#E5E2E1',
        'on-surface-variant': '#DEC1AF',
        'outline-variant': '#574335',
        /* shadcn / assistant-ui semantic tokens */
        foreground: 'var(--foreground)',
        muted: {
          DEFAULT: 'var(--muted)',
          foreground: 'var(--muted-foreground)',
        },
        popover: {
          DEFAULT: 'var(--popover)',
          foreground: 'var(--popover-foreground)',
        },
        primary: {
          DEFAULT: 'var(--primary)',
          foreground: 'var(--primary-foreground)',
        },
        secondary: {
          DEFAULT: 'var(--secondary)',
          foreground: 'var(--secondary-foreground)',
        },
        destructive: 'var(--destructive)',
        input: 'var(--input)',
        ring: 'var(--ring)',
      },
      fontFamily: {
        /* Manrope = primary UI font (Stitch design system) */
        sans: ['var(--font-manrope)', 'system-ui', '-apple-system', 'sans-serif'],
        headline: ['var(--font-manrope)', 'system-ui', 'sans-serif'],
        /* Inter = body/chat content */
        body: ['var(--font-inter)', 'system-ui', '-apple-system', 'sans-serif'],
        mono: ['var(--font-mono)', 'ui-monospace', 'monospace'],
      },
      borderRadius: {
        lg: 'var(--radius)',
        md: 'calc(var(--radius) - 2px)',
        sm: 'calc(var(--radius) - 4px)',
      },
    },
  },
  plugins: [require('@tailwindcss/typography')],
}
